packages:
  - "apps/*"
  - "packages/*"
  - "apps/axis/*"
  - "apps/axis/services/*"

allowBuilds:
  '@mondaycom/apps-cli': true
  '@parcel/watcher': true
  esbuild: true
  postinstall-postinstall: true
