#!/usr/bin/env bash
# PreToolUse hook (Edit|Write|MultiEdit) for the cleanup-executor subagent.
#
# Reads the hook JSON from stdin. exit 0 = allow, exit 2 = block and send stderr back to
# the agent as the reason. This hook is the physical half of "cleanup, twyst-your-status
# ONLY" — the prompts say it, this decides it. It is attached in the executor agent's
# frontmatter, so it constrains cleanup runs without touching normal editing anywhere
# else in the monorepo.
#
# Self-test: bash scripts/cleanup/guard-protected-paths.test.sh
set -uo pipefail

command -v jq >/dev/null 2>&1 || {
  echo "Blocked: jq is required by the cleanup guard and is not installed. Install jq — the guard fails closed on purpose." >&2
  exit 2
}

ROOT="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null)}"
# shellcheck source=./cleanup-env.sh
. "$ROOT/scripts/cleanup/cleanup-env.sh"

INPUT=$(cat)
FILE=$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // .tool_input.edits[0].file_path // empty')
[ -z "$FILE" ] && exit 0

# Normalize to a repo-relative path: hook payloads carry absolute paths, plans and prompts
# carry relative ones, and the rules below must not depend on which one arrived.
case "$FILE" in
  "$ROOT"/*) REL="${FILE#"$ROOT"/}" ;;
  /*)        REL="$FILE" ;;            # absolute and outside the repo → caught by rule 1
  *)         REL="${FILE#./}" ;;
esac

block() { echo "Blocked by the cleanup guard: $1" >&2; exit 2; }

# --- 1. Scope: this package serves exactly one app.
case "$REL" in
  "$CLEANUP_APP_DIR"/*) ;;
  *) block "$FILE is outside $CLEANUP_APP_DIR. This cleanup is scoped to $CLEANUP_APP_SLUG only — an edit anywhere else in the monorepo is not part of it. Skip the finding and report it as out of scope." ;;
esac

# --- 2. Cleanup's own state is always writable.
case "$REL" in
  "$CLEANUP_STATE_DIR"/*) exit 0 ;;
esac

# --- 3. Tests are ground truth, and test-guard locks them repo-wide. A failing test means
# the edit was wrong, never that the test needs adjusting.
case "$(basename "$REL")" in
  *.test.*|*.spec.*|setupTests.js)
    block "$REL is a test file. Tests are the ground truth of this cleanup — they are never edited to accommodate an edit (test-guard locks them repo-wide anyway). If a finding cannot be applied without touching a test, skip it and say so." ;;
esac
case "$REL" in
  */__tests__/*|"$CLEANUP_SRV_DIR"/tests/*|"$CLEANUP_SPA_DIR"/src/test-utils/*)
    block "$REL is test infrastructure. Same rule as test files: never edited during cleanup." ;;
esac

# --- 4. Build output and staged artifacts. server/public is the SPA staged for the
# same-origin monday-code push (round324) — produced by the deploy workflow, never source.
case "$REL" in
  */node_modules/*|*/dist/*|*/build/*|*/coverage/*|*.min.js|*.min.css|*/server/public/*)
    block "$REL is build output or a staged artifact, not source. It is regenerated by the build, so editing it changes nothing and hides the real change." ;;
esac

# --- 5+6. The error/observability boot layer named in apps/twyst-your-status/.error-guard,
# plus the Axiom adapter and the root boundary. scripts/error-wiring-audit.mjs asserts this
# wiring structurally for BOTH surfaces of this app, and the vendored server sink is held
# identical to @mapps/error-kit by packages/error-kit/test/drift.test.ts. knip cannot see
# that a global handler, a sink export or a vendored module is reached from the platform (or
# from another package's test) rather than from an import — so every "unused" finding in
# here is a false positive with an outage behind it.
for protected_file in \
  "$CLEANUP_SPA_DIR/src/utils/logger.js" \
  "$CLEANUP_SPA_DIR/src/utils/globalErrorHandler.js" \
  "$CLEANUP_SPA_DIR/src/utils/axiomLoggerAdapter.js" \
  "$CLEANUP_SPA_DIR/src/hooks/useUiErrorSink.js" \
  "$CLEANUP_SRV_DIR/src/helpers/logger.js" \
  "$CLEANUP_SRV_DIR/src/helpers/process-guards.js" \
  "$CLEANUP_SRV_DIR/src/helpers/axiomServerSink.js"
do
  [ "$REL" = "$protected_file" ] && block "$REL is part of the error/observability boot layer (apps/twyst-your-status/.error-guard, enforced by scripts/error-wiring-audit.mjs; the server sink is additionally drift-locked by packages/error-kit/test/drift.test.ts). Its exports are reached from the platform, not from imports, so 'unused' findings here are false positives. Skip the finding and record it as one."
done
case "$REL" in
  "$CLEANUP_SPA_DIR"/src/components/ErrorBoundary/*)
    block "$REL is the app's root error boundary — the render-phase catch that error-wiring-audit.mjs requires. Never a cleanup target; skip the finding." ;;
esac

# --- 7. Config, docs and manifests are not mechanical cleanup targets.
case "$REL" in
  */CHANGELOG.md)
    block "$REL belongs to the change-tracker flow, not to a cleanup batch." ;;
  */MANIFEST.md|*/.error-guard|"$CLEANUP_APP_DIR"/docs/*)
    block "$REL is documentation or a contract, not source. A cleanup batch never edits it — propose the change in the plan instead." ;;
  *knip.jsonc|*eslint.config.js|*vite.config.js|*postcss.config.js|*build.mjs|*/index.html|*.mappsignore|*.gitignore)
    block "$REL is build/tool configuration. Editing it is not a behaviour-preserving mechanical change (the sourcemap, eager-import and SPA-route-fallback contracts all live in these files). Propose it in the plan; a human decides." ;;
  */pnpm-lock.yaml|*package-lock.json|*yarn.lock)
    block "$REL is a lockfile. Dependency batches run 'pnpm remove --filter <workspace> <pkg>', which updates it correctly." ;;
esac

# --- 8. What is left: application source, and the two manifests a dependency batch edits.
case "$REL" in
  "$CLEANUP_SPA_DIR"/src/*) exit 0 ;;
  "$CLEANUP_SRV_DIR"/src/*) exit 0 ;;
  "$CLEANUP_SPA_DIR"/package.json|"$CLEANUP_SRV_DIR"/package.json) exit 0 ;;
esac

block "$REL is inside $CLEANUP_APP_DIR but not in the cleanup allowlist (src/, server/src/, the two package.json files, .cleanup/). Skip the finding rather than working around this guard."
