#!/usr/bin/env bash
# Shared path decision for the twyst-your-status cleanup guards.
#
# ONE function, TWO callers: guard-protected-paths.sh (PreToolUse on Edit|Write|MultiEdit)
# and guard-bash-ops.py (PreToolUse on Bash). They existed as one Edit-only guard until a
# pre-approval refutation pass pointed out the hole: a dead-file batch deletes files with
# `rm`, which never reaches an Edit hook, so the scope guard could not see the single most
# destructive operation in the whole workflow. Keeping the decision here means a rule can
# never drift between the two surfaces.
#
# Usage:  cleanup_path_verdict <path>       # abs or repo-relative
#   prints "ALLOW"                          → the cleanup may touch this path
#   prints "BLOCK|<reason>"                 → it may not, and the reason is agent-facing
# Never exits; the caller decides what to do with the verdict.
#
# Requires: CLEANUP_* variables from cleanup-env.sh, and ROOT set to the repo root.

cleanup_path_verdict() {
  local file="$1" rel base

  [ -z "$file" ] && { echo "ALLOW"; return; }

  # Normalize to a repo-relative path: hook payloads carry absolute paths, plans and
  # commands carry relative ones, and no rule below may depend on which arrived.
  case "$file" in
    "$ROOT"/*) rel="${file#"$ROOT"/}" ;;
    /*)        rel="$file" ;;              # absolute, outside the repo → rule 1
    *)         rel="${file#./}" ;;
  esac

  # --- 1. Scope: this package serves exactly one app.
  case "$rel" in
    "$CLEANUP_APP_DIR"/*) ;;
    *) echo "BLOCK|$file is outside $CLEANUP_APP_DIR. This cleanup is scoped to $CLEANUP_APP_SLUG only — touching anything else in the monorepo is not part of it. Skip the finding and report it as out of scope."; return ;;
  esac

  # --- 2. Cleanup's own state is always writable.
  case "$rel" in
    "$CLEANUP_STATE_DIR"/*) echo "ALLOW"; return ;;
  esac

  # --- 3. Tests are ground truth, and test-guard locks them repo-wide. A failing test means
  # the edit was wrong, never that the test needs adjusting.
  base="$(basename "$rel")"
  case "$base" in
    *.test.*|*.spec.*|setupTests.js)
      echo "BLOCK|$rel is a test file. Tests are the ground truth of this cleanup — they are never edited, moved or deleted to accommodate a change (test-guard locks them repo-wide anyway). If a finding cannot be applied without touching a test, skip it and say so."; return ;;
  esac
  case "$rel" in
    */__tests__/*|"$CLEANUP_SPA_DIR"/src/test-utils/*)
      echo "BLOCK|$rel is test infrastructure. Same rule as test files: never touched during cleanup."; return ;;
  esac
  if [ -n "${CLEANUP_SRV_DIR:-}" ]; then
    case "$rel" in
      "$CLEANUP_SRV_DIR"/tests/*)
        echo "BLOCK|$rel is test infrastructure. Same rule as test files: never touched during cleanup."; return ;;
    esac
  fi

  # --- 4. Build output and staged artifacts. server/public is the SPA staged for the
  # same-origin monday-code push (round324) — produced by the deploy workflow, never source.
  case "$rel" in
    */node_modules/*|*/dist/*|*/build/*|*/coverage/*|*.min.js|*.min.css|*/server/public/*)
      echo "BLOCK|$rel is build output or a staged artifact, not source. It is regenerated by the build, so changing it changes nothing and hides the real change."; return ;;
  esac

  # --- 5+6. The error/observability boot layer, declared PER APP in the env file
  # (CLEANUP_PROTECTED_FILES, one path per line; CLEANUP_PROTECTED_DIRS protect whole
  # subtrees — the root error boundary lives there). scripts/error-wiring-audit.mjs
  # asserts this wiring structurally, and knip cannot see that a global handler, a sink
  # export or a vendored module is reached from the platform (or from another package's
  # test) rather than from an import — so every "unused" finding in here is a false
  # positive with an outage behind it.
  local protected_file protected_dir
  while IFS= read -r protected_file; do
    [ -z "$protected_file" ] && continue
    if [ "$rel" = "$protected_file" ]; then
      echo "BLOCK|$rel is part of the error/observability boot layer (declared in scripts/cleanup/env/${CLEANUP_APP_SLUG}.sh, enforced by scripts/error-wiring-audit.mjs). Its exports are reached from the platform, not from imports, so 'unused' findings here are false positives. Skip the finding and record it as one."
      return
    fi
  done <<EOF_PROTECTED
${CLEANUP_PROTECTED_FILES:-}
EOF_PROTECTED
  while IFS= read -r protected_dir; do
    [ -z "$protected_dir" ] && continue
    case "$rel" in
      "$protected_dir"/*)
        echo "BLOCK|$rel is inside a protected error/observability directory ($protected_dir — the render-phase catch layer error-wiring-audit.mjs requires). Never a cleanup target; skip the finding."; return ;;
    esac
  done <<EOF_PROTECTED_DIRS
${CLEANUP_PROTECTED_DIRS:-}
EOF_PROTECTED_DIRS

  # --- 7. Config, docs and manifests are not mechanical cleanup targets.
  case "$rel" in
    */CHANGELOG.md)
      echo "BLOCK|$rel belongs to the change-tracker flow, not to a cleanup batch."; return ;;
    */MANIFEST.md|*/.error-guard|"$CLEANUP_APP_DIR"/docs/*)
      echo "BLOCK|$rel is documentation or a contract, not source. A cleanup batch never edits it — propose the change in the plan instead."; return ;;
    *knip.jsonc|*eslint.config.js|*vite.config.js|*postcss.config.js|*tailwind.config.js|*build.mjs|*/index.html|*.mappsignore|*.gitignore)
      echo "BLOCK|$rel is build/tool configuration. Changing it is not a behaviour-preserving mechanical edit (the sourcemap, eager-import and SPA-route-fallback contracts all live in these files). Propose it in the plan; a human decides."; return ;;
    */pnpm-lock.yaml|*package-lock.json|*yarn.lock)
      echo "BLOCK|$rel is a lockfile. Dependency batches run 'pnpm remove --filter <workspace> <pkg>', which updates it correctly."; return ;;
  esac

  # --- 8. What is left: application source, and the manifest(s) a dependency batch edits.
  # The server pair exists only for apps that HAVE a server workspace.
  case "$rel" in
    "$CLEANUP_SPA_DIR"/src/*) echo "ALLOW"; return ;;
    "$CLEANUP_SPA_DIR"/package.json) echo "ALLOW"; return ;;
  esac
  if [ -n "${CLEANUP_SRV_DIR:-}" ]; then
    case "$rel" in
      "$CLEANUP_SRV_DIR"/src/*) echo "ALLOW"; return ;;
      "$CLEANUP_SRV_DIR"/package.json) echo "ALLOW"; return ;;
    esac
  fi

  echo "BLOCK|$rel is inside $CLEANUP_APP_DIR but not in the cleanup allowlist (src/,${CLEANUP_SRV_DIR:+ server src/,} the package.json manifest(s), .cleanup/). Skip the finding rather than working around this guard."
}
